### ISSUE TITLE
Require image for ARM64 architecture

### ISSUE THREAD

**Issue by odidev** [laurentverbruggen/concourse-git-semver-tag-resource#14]
Hi Team,

I am trying to use **laurentverbruggen/concourse-git-semver-tag-resource** on ARM64 architecture but it seems the arm64 tag is not available in Docker Hub.

I have successfully built the image on arm64 platform using the command **docker build -t <image_name> .**

I have used buildx in Github actions to build and push the image for both platforms.

**Commit Link** - https://github.com/odidev/concourse-git-semver-tag-resource/commit/45db547b8b3bcd5007fece503eb0cbe0eea4b05b

**Github actions Link** - https://github.com/odidev/concourse-git-semver-tag-resource/runs/1950580631?check_suite_focus=true

**Dockerhub Link** - https://hub.docker.com/repository/docker/odidev/concourse-git-semver-tag-resource

Do you have any plans on releasing arm64 images?

Please share your opinion on this. If interested, I will raise a PR.

**Comment by laurentverbruggen** [comment]
I merged and built your PR
